## Дятлова Дарья

In [135]:
import sklearn

In [136]:
import pandas as pd
import numpy as np
from typing import List
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split

In [137]:
test_path = '/Users/diat.lov/Downloads/prod_st_data/hw1/test.csv'
train_path_one = '/Users/diat.lov/Downloads/prod_st_data/hw1/train01.csv'
train_path_two = '/Users/diat.lov/Downloads/prod_st_data/hw1//train02.csv'

In [289]:
train_part_one = pd.read_csv(train_path_one, sep=';')
train_part_two = pd.read_csv(train_path_two, sep=';')
test_data = pd.read_csv(test_path, sep=';')

In [5]:
assert len(train_part_one.id.unique()) == train_part_one.shape[0]

In [7]:
train_part_two.head(1)

id  y                   x1          x2  \
0 -9196902500682081897  0 -2201458060675810556  01.09.2008   

                    x3   x4            x5                   x6  x7  \
0  6312572492787112517  184 -6.347413e+18 -3150357754345161454   0   

                                                  x8  ...  \
0  [607.29999999999995 66.569999999999993 254.770...  ...   

                              x33                             x34  \
0  [nan, nan, nan, nan, nan, nan]  [nan, nan, 1.0, 2.0, 1.0, nan]   

                                          x35  \
0  [67.64, 67.64, 67.64, 67.64, 67.64, 67.64]   

                                                x36  \
0  [199.65, 199.65, 199.65, 199.65, 199.65, 199.65]   

                              x37                             x38  \
0  [nan, nan, nan, nan, nan, nan]  [nan, nan, nan, nan, nan, nan]   

                                          x39                             x40  \
0  [80.46, 80.46, 80.46, 80.46, 80.46, 80.46]  [nan, nan, nan, nan, nan, nan]   

                              x41                             x42  
0  [nan, nan, nan, nan, nan, nan]  [nan, nan, nan, nan, nan, nan]  

[1 rows x 44 columns]

In [8]:
train_part_two.shape

(93189, 44)

In [9]:
print(f'rate of total users left in first 6 months: {len(train_part_one.y[train_part_one.y == 1]) / train_part_one.shape[0]}')
print(f'rate of total users left in second 6 months: {len(train_part_two.y[train_part_two.y == 1]) / train_part_two.shape[0]}')

rate of total users left in first 6 months: 0.025177821764948993
rate of total users left in second 6 months: 0.024187404092757728


In [20]:
np.unique(train_part_one.x5, return_counts=True)

(array([-8.55246375e+18, -8.52300049e+18, -8.46517905e+18, -6.98633012e+18,
        -6.34741325e+18, -5.15056141e+18, -4.70010804e+18, -3.80824545e+18,
        -3.16769564e+18,  1.76960021e+18,  1.88811659e+18,  3.05255731e+18,
         3.69580186e+18,  4.09361301e+18,  5.41747352e+18,  6.43922739e+18,
         6.85636664e+18,  7.01335969e+18,  7.20436336e+18,  7.59905378e+18,
         8.87840015e+18,             nan]),
 array([   16,    69, 10776,   301, 24518,  5787,  2057,    40,   993,
          438,  1201,  5458,   148,   395,  4524,  6422,  6304,   244,
         2128,  4297,  2668, 13162]))

In [31]:
np.unique(train_part_one[train_part_one.y == 1].x5, return_counts=True)

2

In [29]:
np.unique(train_part_one.x5, return_counts=True)

(array([-8.55246375e+18, -8.52300049e+18, -8.46517905e+18, -6.98633012e+18,
        -6.34741325e+18, -5.15056141e+18, -4.70010804e+18, -3.80824545e+18,
        -3.16769564e+18,  1.76960021e+18,  1.88811659e+18,  3.05255731e+18,
         3.69580186e+18,  4.09361301e+18,  5.41747352e+18,  6.43922739e+18,
         6.85636664e+18,  7.01335969e+18,  7.20436336e+18,  7.59905378e+18,
         8.87840015e+18,             nan]),
 array([   16,    69, 10776,   301, 24518,  5787,  2057,    40,   993,
          438,  1201,  5458,   148,   395,  4524,  6422,  6304,   244,
         2128,  4297,  2668, 13162]))

In [142]:
df_normolized_part_one = pd.DataFrame({})
df_normolized_part_one['id'] = train_part_one.id
for col in ['x1', 'x3', 'x4', 'x5', 'x6', 'x7']:
    df_normolized_part_one[col + '_norm'] = (train_part_one[col] - train_part_one[col].mean()) / train_part_one[col].std()  
df_normolized_part_one['y'] = train_part_one.y

df_normolized_part_two = pd.DataFrame({})
df_normolized_part_two['id'] = train_part_two.id
for col in ['x1', 'x3', 'x4', 'x5', 'x6', 'x7']:
    df_normolized_part_two[col + '_norm'] = (train_part_two[col] - train_part_two[col].mean()) / train_part_two[col].std()  
df_normolized_part_two['y'] = train_part_two.y

In [291]:
df_normolized_test = pd.DataFrame({})
df_normolized_test['id'] = test_data.id
for col in ['x1', 'x3', 'x4', 'x5', 'x6', 'x7']:
    df_normolized_test[col + '_norm'] = (test_data[col] - test_data[col].mean()) / test_data[col].std()  

In [143]:
df_normolized_y1_part_one = df_normolized_part_one[df_normolized_part_one.y == 1]
df_normolized_y0_part_one = df_normolized_part_one[df_normolized_part_one.y == 0]

df_normolized_y1_part_two = df_normolized_part_two[df_normolized_part_two.y == 1]
df_normolized_y0_part_two = df_normolized_part_two[df_normolized_part_two.y == 0]

In [144]:
df_normolized_y1_part_one = df_normolized_y1_part_one.fillna(df_normolized_part_one.groupby('y').mean().x5_norm[1])
df_normolized_y0_part_one = df_normolized_y0_part_one.fillna(df_normolized_part_one.groupby('y').mean().x5_norm[0])

df_normolized_y1_part_two = df_normolized_y1_part_two.fillna(df_normolized_part_two.groupby('y').mean().x5_norm[1])
df_normolized_y0_part_two = df_normolized_y0_part_two.fillna(df_normolized_part_two.groupby('y').mean().x5_norm[0])

In [145]:
new_df_part_one = pd.concat([df_normolized_y1_part_one, df_normolized_y0_part_one])
new_df_part_two = pd.concat([df_normolized_y1_part_two, df_normolized_y0_part_two])

In [146]:
def convert_to_list(input_arr):
    res = []
    for sample in input_arr:
        l = []
        for symbol in sample:
            try:
                l.append(float(symbol))
            except Exception:
                pass
        if len(l) < 6:
            res.append(np.array(l + [0 for _ in range(6 - len(l))]).astype(np.float32))
            assert len(res[-1]) == 6
        else:
            res.append(np.array(l[:6]).astype(np.float32))
    return res   

In [147]:
nested_column_names = train_part_one.columns[11:]

In [148]:
df_averaged_feature_names_part_one = pd.DataFrame({})
df_averaged_feature_names_part_one['id'] = train_part_one.id
df_averaged_feature_names_part_one['y'] = train_part_one.y

df_averaged_feature_names_part_two = pd.DataFrame({})
df_averaged_feature_names_part_two['id'] = train_part_two.id
df_averaged_feature_names_part_two['y'] = train_part_two.y

In [292]:
df_avg_test = pd.DataFrame({})
df_avg_test['id'] = df_normolized_test.id

In [149]:
for col in nested_column_names:
    df_averaged_feature_names_part_one[col + '_avg'] = np.mean(convert_to_list(train_part_one[col].to_list()), axis=1)
    df_averaged_feature_names_part_two[col + '_avg'] = np.mean(convert_to_list(train_part_two[col].to_list()), axis=1)

In [293]:
for col in nested_column_names:
    df_avg_test[col + '_avg'] = np.mean(convert_to_list(test_data[col].to_list()), axis=1)

In [150]:
train_part_one_to_split = df_averaged_feature_names_part_one.merge(new_df_part_one, on='id', how='inner')
train_part_two_to_split = df_averaged_feature_names_part_two.merge(new_df_part_two, on='id', how='inner')

In [300]:
test_data_to_split = df_avg_test.merge(df_normolized_test, on='id', how='inner')

In [301]:
test_data_to_split.head(1)

id  x10_avg  x11_avg  x12_avg   x13_avg  x14_avg  x15_avg  \
0 -9196902500682081904      0.0      0.0      0.0  0.333333      0.0      0.0   

   x16_avg  x17_avg   x18_avg  ...   x39_avg  x40_avg  x41_avg  x42_avg  \
0      0.0      0.0  4.833333  ...  4.333333      0.0      0.0      0.0   

    x1_norm   x3_norm   x4_norm   x5_norm   x6_norm   x7_norm  
0  0.135947  0.071251  0.570143 -0.810711  0.631129 -0.773302  

[1 rows x 40 columns]

In [151]:
train_part_one_to_split.drop(columns=['y_y'], inplace=True)
train_part_two_to_split.drop(columns=['y_y'], inplace=True)

In [152]:
train_part_one_to_split = train_part_one_to_split.rename(columns={"y_x": "y"})
train_part_two_to_split = train_part_two_to_split.rename(columns={"y_x": "y"})

In [153]:
train_part_one_to_split

id  y   x10_avg   x11_avg   x12_avg   x13_avg  \
0     -9196902500682081904  0  0.000000  0.000000  0.000000  0.500000   
1     -9196902500682081900  0  0.000000  0.000000  0.000000  0.000000   
2     -9196902500682081899  0  0.000000  0.333333  1.166667  0.000000   
3     -9196902500682081897  0  0.000000  0.000000  0.000000  0.000000   
4     -9196902500681081897  0  0.000000  0.000000  0.500000  0.000000   
...                    ... ..       ...       ...       ...       ...   
91941  9162040885607725763  0  0.000000  0.000000  0.000000  0.000000   
91942  9162040885607725766  0  0.000000  0.000000  0.000000  0.000000   
91943  9162040885608725764  0  0.166667  0.000000  1.333333  0.000000   
91944  9162040885608725770  0  0.000000  0.500000  0.000000  0.000000   
91945  9162040885609725775  0  0.000000  0.000000  0.000000  0.666667   

        x14_avg   x15_avg   x16_avg   x17_avg  ...   x39_avg  x40_avg  \
0      0.000000  0.166667  0.000000  0.166667  ...  4.333333      0.0   
1      0.000000  0.000000  0.166667  0.000000  ...  2.333333      0.0   
2      0.000000  0.000000  0.000000  0.000000  ...  4.333333      0.0   
3      0.000000  0.000000  0.000000  0.000000  ...  4.333333      0.0   
4      0.000000  0.000000  0.000000  0.000000  ...  4.333333      0.0   
...         ...       ...       ...       ...  ...       ...      ...   
91941  0.000000  0.000000  0.000000  0.000000  ...  4.333333      0.0   
91942  0.000000  0.000000  0.000000  0.000000  ...  4.333333      0.0   
91943  0.000000  0.000000  0.000000  0.000000  ...  0.000000      0.0   
91944  0.666667  0.000000  0.000000  0.000000  ...  4.333333      0.0   
91945  0.000000  0.000000  0.500000  0.000000  ...  4.333333      0.0   

       x41_avg  x42_avg   x1_norm   x3_norm   x4_norm   x5_norm   x6_norm  \
0          0.0      0.0  0.146329  0.070090  0.511438 -0.816230  0.636315   
1          0.0      0.0  0.146329 -3.513818  0.511438 -1.146805 -1.364314   
2          0.0      0.0  0.146329  0.070090  0.340303  1.020228 -0.772798   
3          0.0      0.0  0.146329  0.070090  0.511438 -0.816230 -0.337783   
4          0.0      0.0  0.146329  0.070090  0.438094  1.244834  1.165308   
...        ...      ...       ...       ...       ...       ...       ...   
91941      0.0      0.0  2.034117  0.070090  0.511438  0.002790  1.067166   
91942      0.0      0.0  2.034117  0.070090  0.511438  0.002790  1.945735   
91943      0.0      0.0 -1.428925  0.070090  0.095826  1.360765  0.636315   
91944      0.0      0.0 -1.428925  0.070090  0.511438  1.360765  0.636315   
91945      0.0      0.0  1.033297  0.070090  0.511438 -0.816230  0.597449   

        x7_norm  
0     -0.727861  
1     -0.727861  
2     -0.150518  
3     -0.727861  
4      0.426826  
...         ...  
91941 -0.727861  
91942 -0.727861  
91943 -0.150518  
91944 -0.727861  
91945 -0.727861  

[91946 rows x 41 columns]

In [154]:
train_part_two_to_split

id  y   x10_avg  x11_avg   x12_avg   x13_avg  \
0     -9196902500682081897  0  0.000000      0.0  0.000000  0.000000   
1     -9196902500682081892  0  0.000000      0.0  0.000000  0.000000   
2     -9196902500681081898  0  0.000000      0.0  1.500000  0.166667   
3     -9196902500681081897  0  0.000000      0.0  0.500000  0.000000   
4     -9196902500681081889  0  0.000000      0.0  0.000000  0.166667   
...                    ... ..       ...      ...       ...       ...   
93184  9162040885608725764  0  0.166667      0.0  1.333333  0.000000   
93185  9162040885608725769  0  0.000000      0.0  1.166667  0.000000   
93186  9162040885608725770  0  0.000000      0.5  0.000000  0.000000   
93187  9162040885608725772  0  0.000000      0.0  0.000000  0.000000   
93188  9162040885609725775  0  0.000000      0.0  0.000000  0.166667   

        x14_avg  x15_avg   x16_avg  x17_avg  ...   x39_avg  x40_avg  x41_avg  \
0      0.000000      0.0  0.000000      0.0  ...  4.333333      0.0      0.0   
1      0.000000      0.0  0.000000      0.0  ...  0.000000      0.0      0.0   
2      0.166667      0.0  0.000000      0.0  ...  0.000000      0.0      0.0   
3      0.000000      0.0  0.000000      0.0  ...  4.333333      0.0      0.0   
4      0.000000      0.0  0.000000      0.0  ...  4.333333      0.0      0.0   
...         ...      ...       ...      ...  ...       ...      ...      ...   
93184  0.000000      0.0  0.000000      0.0  ...  0.000000      0.0      0.0   
93185  0.000000      0.0  0.000000      0.0  ...  3.000000      0.0      0.0   
93186  0.666667      0.0  0.000000      0.0  ...  4.333333      0.0      0.0   
93187  0.000000      0.0  0.000000      0.0  ...  4.333333      0.0      0.0   
93188  0.000000      0.0  0.166667      0.0  ...  4.333333      0.0      0.0   

       x42_avg   x1_norm   x3_norm   x4_norm   x5_norm   x6_norm   x7_norm  
0          0.0  0.144024  0.070414  0.549187 -0.812987 -0.336746 -0.755672  
1          0.0  0.144024  0.070414  0.549187 -0.812987 -1.123224 -0.755672  
2          0.0  0.144024  0.070414 -2.415469 -1.143430 -1.363796  1.506536  
3          0.0  0.144024  0.070414  0.478600  1.247253  1.167106  0.375432  
4          0.0  0.144024  0.070414  0.549187  0.653729 -1.311236 -0.755672  
...        ...       ...       ...       ...       ...       ...       ...  
93184      0.0 -1.426596  0.070414  0.149194  1.363137  0.637844 -0.190120  
93185      0.0 -1.426596  0.070414 -3.591919  1.363137 -0.236896 -0.755672  
93186      0.0 -1.426596  0.070414  0.549187  1.363137  0.637844 -0.755672  
93187      0.0 -1.426596  0.070414  0.549187  1.363137  0.970087 -0.755672  
93188      0.0  1.028382  0.070414  0.549187 -0.812987  0.598959 -0.755672  

[93189 rows x 41 columns]

In [161]:
part_one_stat = pd.DataFrame((train_part_one_to_split == 0).sum(axis=0) / train_part_one_to_split.shape[0])

In [167]:
part_one_stat[part_one_stat[0] < 0.3].index

Index(['id', 'x28_avg', 'x34_avg', 'x35_avg', 'x36_avg', 'x39_avg', 'x1_norm',
       'x3_norm', 'x4_norm', 'x5_norm', 'x6_norm', 'x7_norm'],
      dtype='object')

In [180]:
part_two_stat = pd.DataFrame((train_part_two_to_split == 0).sum(axis=0) / train_part_two_to_split.shape[0])

In [181]:
part_two_stat[part_two_stat[0] < 0.3].index

Index(['id', 'x28_avg', 'x34_avg', 'x35_avg', 'x36_avg', 'x39_avg', 'x1_norm',
       'x3_norm', 'x4_norm', 'x5_norm', 'x6_norm', 'x7_norm'],
      dtype='object')

In [186]:
selected_part_one = train_part_one_to_split[list(part_one_stat[part_one_stat[0] < 0.3].index) + ['y']]

In [190]:
selected_part_one[selected_part_one.y == 0].shape

(89631, 13)

In [192]:
selected_part_one[selected_part_one.y == 1].shape[0] / selected_part_one.shape[0]

0.025177821764948993

In [193]:
selected_part_one_zeros = selected_part_one.sample(frac=0.03, replace=False, random_state=42)

In [195]:
df_balanced = selected_part_one_zeros.append(selected_part_one[selected_part_one.y == 1])

In [196]:
df_balanced.shape

(5073, 13)

In [299]:
test_data_to_split.head(1)

id  x10_avg  x11_avg  x12_avg   x13_avg  x14_avg  x15_avg  \
0 -9196902500682081904      0.0      0.0      0.0  0.333333      0.0      0.0   

   x16_avg  x17_avg   x18_avg  ...                             x33  \
0      0.0      0.0  4.833333  ...  [nan, nan, nan, nan, nan, nan]   

                              x34                                         x35  \
0  [1.0, nan, nan, 1.0, nan, 6.0]  [67.64, 67.64, 67.64, 67.64, 67.64, 67.64]   

                                                x36  \
0  [224.79, 224.79, 224.79, 224.79, 224.79, 224.79]   

                              x37                             x38  \
0  [nan, nan, nan, nan, nan, nan]  [nan, nan, nan, nan, nan, nan]   

                                          x39                             x40  \
0  [80.46, 80.46, 80.46, 80.46, 80.46, 80.46]  [nan, nan, nan, nan, nan, nan]   

                              x41                             x42  
0  [nan, nan, nan, nan, nan, nan]  [nan, nan, nan, nan, nan, nan]  

[1 rows x 76 columns]

In [303]:
test_data_final = test_data_to_split[part_one_stat[part_one_stat[0] < 0.3].index]

In [ ]:
# selected_part_two = train_part_two_to_split[list(part_two_stat[part_two_stat[0] < 0.3].index)]
# selected_part_two.rename(columns={'x28_avg': 'x28_avg_2'})

In [279]:
X_train, X_test, y_train, y_test = train_test_split(df_balanced.drop(columns=['y']),
                                                    df_balanced.y, 
                                                    test_size=0.33, 
                                                    random_state=42)

In [280]:
from catboost import Pool, CatBoostClassifier

In [281]:
train_dataset = Pool(data=X_train, label=y_train)

eval_dataset = Pool(data=X_test, label=y_test)

In [306]:
model = CatBoostClassifier(iterations=5)

model.fit(train_dataset)
preds_class = model.predict(train_dataset)
pred_probas = model.predict_proba(train_dataset)

Learning rate set to 0.5
0:	learn: 0.5757665	total: 3.04ms	remaining: 12.2ms
1:	learn: 0.5226115	total: 4.91ms	remaining: 7.36ms
2:	learn: 0.4925119	total: 6.66ms	remaining: 4.44ms
3:	learn: 0.4594498	total: 9.25ms	remaining: 2.31ms
4:	learn: 0.4497864	total: 11.9ms	remaining: 0us


In [310]:
print(preds_class[:10], pred_probas[:10][:, 1])

[0 0 0 1 0 1 0 1 1 1] [0.49140046 0.19284971 0.42592181 0.77104431 0.1601022  0.87598923
 0.29343805 0.74910557 0.757692   0.79261494]


In [283]:
assert len(preds_class) == len(y_train)

In [284]:
len(np.where(np.array(preds_class).astype(int) == np.array(y_train).astype(int))[0]) / len(preds_class)

0.8072395526780459

In [285]:
true_pred = np.where(np.array(preds_class).astype(int) == np.array(y_train).astype(int))[0]

In [286]:
true_pred_one = np.where(preds_class[true_pred] == 1)[0]

In [287]:
len(true_pred_one) / len(np.where(y_train == 1)[0])

0.7927815805849409

In [ ]:
# 0.24, 0.79 vs 0.98 0.8

In [311]:
test_pred = model.predict_proba(test_data_final)[:, 1]

In [312]:
test_pred

array([0.22494067, 0.20509774, 0.73851402, ..., 0.16356988, 0.44526065,
       0.1601022 ])

In [313]:
res_df = pd.DataFrame({'id': test_data.id, 'result': test_pred})

In [315]:
res_df.to_csv('/Users/diat.lov/Downloads/prod_st_data/hw1/result.csv', sep=';', index=False)